# Generated by Django 5.1.4 on 2025-08-06 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name_plural': '03 Teachers'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='index_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Index Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible on Website'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nid',
            field=models.CharField(blank=True, max_length=20, verbose_name='NID Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Educational Qualification'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(blank=True, choices=[('MPO', 'MPO'), ('Non-MPO', 'Non-MPO')], default='Non-MPO', max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
