# Generated by Django 5.1.4 on 2025-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0002_alter_teacher_options_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='indexing_of_mpo',
            field=models.DateField(blank=True, null=True, verbose_name='Indexing Date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, verbose_name='Educational Qualification'),
        ),
    ]
