# Generated by Django 5.1.4 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0003_teacher_dob_teacher_indexing_of_mpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='major_subject',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Major Subject'),
        ),
    ]
