# Generated by Django 5.1.4 on 2025-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0005_teacher_allow_result_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='only_marks_input',
            field=models.BooleanField(default=False, verbose_name='Allow Only Marks Input'),
        ),
    ]
