# Generated by Django 5.1.4 on 2025-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0006_teacher_only_marks_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='allow_all_subject',
            field=models.BooleanField(default=False, verbose_name='Enable All Subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='allow_result_processing',
            field=models.BooleanField(default=False, verbose_name='Enable Result Processing'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='allow_students_info',
            field=models.BooleanField(default=False, verbose_name='Enable Student Info'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='only_marks_input',
            field=models.BooleanField(default=False, verbose_name='Enable Marks Input Only'),
        ),
    ]
