# Generated by Django 5.1.4 on 2025-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0007_alter_teacher_allow_all_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
