# Generated by Django 5.1.4 on 2025-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0008_student_fathers_name_student_mothers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_whatsapp',
            field=models.BooleanField(default=False, help_text='Is this a WhatsApp number?'),
        ),
    ]
