# Generated by Django 5.1.4 on 2025-09-10 10:23

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0009_teacher_bangla_name_teacher_is_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cropped_picture',
            field=image_cropping.fields.ImageRatioField('picture', '300x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped picture'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cropped_signature',
            field=image_cropping.fields.ImageRatioField('signature', '300x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped signature'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_teacher_picture),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_teacher_signature),
        ),
    ]
