# Generated by Django 5.1.4 on 2025-09-10 12:57

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0010_teacher_cropped_picture_teacher_cropped_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cropped_signature',
            field=image_cropping.fields.ImageRatioField('signature', '300x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped signature'),
        ),
    ]
