# Generated by Django 5.1.4 on 2025-09-10 14:07

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0011_alter_teacher_cropped_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cropped_picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='cropped_signature',
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture_cropped',
            field=image_cropping.fields.ImageRatioField('picture', '300x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='picture cropped'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature_cropped',
            field=image_cropping.fields.ImageRatioField('signature', '300x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='signature cropped'),
        ),
    ]
