# Generated by Django 5.1.4 on 2025-09-10 14:22

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0012_remove_teacher_cropped_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='picture_cropped',
            field=image_cropping.fields.ImageRatioField('picture', '300x380', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='picture cropped'),
        ),
    ]
