# Generated by Django 5.1.4 on 2025-09-12 13:25

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0013_alter_teacher_picture_cropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture_cropped',
            field=image_cropping.fields.ImageRatioField('picture', '300x380', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='picture cropped'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_student_pictures),
        ),
    ]
