# Generated by Django 5.1.4 on 2025-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0014_student_picture_cropped_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('assistant_teacher', 'Assistant Teacher'), ('assistant_head_teacher', 'Assistant Head Teacher'), ('head_teacher', 'Head Teacher'), ('lecturer', 'Lecturer'), ('demonstrator', 'Demonstrator'), ('senior_lecturer', 'Senior Lecturer'), ('assistant_professor', 'Assistant Professor'), ('professor', 'Professor'), ('principal', 'Principal'), ('lab_assistant', 'Lab Assistant'), ('office_assistant', 'Office Assistant'), ('office_assistant_cum_typist', 'Office Assistant Cum Typist'), ('assistant_librarian', 'Assistant Librarian'), ('mali', 'Mali'), ('nanny', 'Nanny'), ('4th_grade_employee', '4th Grade Employee'), ('Cleaner', 'Cleaner')], max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.CharField(blank=True, choices=[('MPO', 'MPO'), ('Non-MPO', 'Non-MPO')], default='MPO', max_length=20, null=True, verbose_name='Section'),
        ),
    ]
