# Generated by Django 5.1.4 on 2025-11-04 15:47

import backend.utils
import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0015_alter_teacher_designation_alter_teacher_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_or_institute', models.CharField(max_length=255)),
                ('group_or_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('image', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_teacher_certificate, verbose_name='Certificate')),
                ('image_cropped', image_cropping.fields.ImageRatioField('image', '800x1120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped')),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='ims_02_account.examination')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='ims_02_account.teacher')),
            ],
            options={
                'verbose_name': 'Educational Qualification',
                'verbose_name_plural': 'Educational Qualifications',
                'ordering': ['passing_year'],
            },
        ),
    ]
