# Generated by Django 5.1.4 on 2025-11-04 16:00

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0016_examination_teachereducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_teacher_certificate),
        ),
    ]
