# Generated by Django 5.1.4 on 2025-11-04 16:05

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0019_alter_teachereducation_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachereducation',
            name='certificate',
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_teacher_certificate, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '800x1120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
    ]
