# Generated by Django 5.1.4 on 2025-11-07 14:23

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0022_remove_teachereducation_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '800x1120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Certificate Cropped'),
        ),
    ]
