# Generated by Django 5.1.4 on 2025-11-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0023_alter_teachereducation_image_cropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachereducation',
            name='ntrca_batch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
