# Generated by Django 5.1.4 on 2025-11-10 02:43

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0024_teachereducation_ntrca_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '3508x2480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Certificate Cropped'),
        ),
    ]
