# Generated by Django 5.1.4 on 2025-12-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0025_alter_teachereducation_image_cropped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClassHistory',
        ),
    ]
