# Generated by Django 5.1.4 on 2025-12-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0017_shift'),
        ('ims_02_account', '0026_delete_studentclasshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text="True if this history row represents the student's current class (to_date is null).")),
                ('promotion_batch', models.CharField(blank=True, help_text="Optional batch id/name for bulk promotions (e.g. '2025-promotion-6to7').", max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.class', verbose_name='Class')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.group', verbose_name='Group')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.institute', verbose_name='Institute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.section', verbose_name='Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='ims_02_account.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '05 StudentClassHistories',
                'ordering': ['-from_date'],
                'indexes': [models.Index(fields=['student', 'is_current'], name='ims_02_acco_student_0679d3_idx'), models.Index(fields=['institute', 'year', 'class_instance', 'section'], name='ims_02_acco_institu_9742b6_idx')],
            },
        ),
    ]
