# Generated by Django 5.1.4 on 2025-07-22 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsrecipient', to='ims_01_institute.institute', verbose_name='Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipient', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsrecipient', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '02 SMSRecipients',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='ims_07_sms.smsrecipient')),
            ],
            options={
                'verbose_name_plural': '03 SMSLogs',
            },
        ),
        migrations.CreateModel(
            name='SMSRecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsrecipientgroup', to='ims_01_institute.institute', verbose_name='Institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsrecipientgroup', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '01 SMSRecipientGroups',
            },
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ims_07_sms.smsrecipientgroup'),
        ),
        migrations.CreateModel(
            name='BulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bulk_sms', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulksms', to='ims_01_institute.institute', verbose_name='Institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulksms', to='ims_01_institute.year', verbose_name='Year')),
                ('recipients', models.ManyToManyField(blank=True, related_name='bulk_sms', to='ims_07_sms.smsrecipient')),
                ('groups', models.ManyToManyField(blank=True, related_name='bulk_sms', to='ims_07_sms.smsrecipientgroup')),
            ],
            options={
                'verbose_name_plural': '04 BulkSMSs',
            },
        ),
    ]
