# Generated by Django 5.1.4 on 2025-07-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': '03 Class Names',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': '05 Group Names',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_in_english', models.CharField(max_length=255)),
                ('institute_code', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institute_logos/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='institute_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_of_class_teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_of_class_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_of_class_guardian', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_of_class_guardian_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_of_head', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_of_head_bangla', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '01 Institutes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': '06 Section Names',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('day', 'Day'), ('evening', 'Evening')], max_length=20)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='ims_01_institute.classname')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ims_01_institute.institute')),
            ],
            options={
                'verbose_name_plural': '04 Classes',
                'ordering': ['year', 'class_name__code', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('short_name', models.CharField(default='N', max_length=10)),
                ('class_name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': '07 Subject Names',
                'ordering': ['class_name', 'code'],
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='ims_01_institute.institute')),
            ],
            options={
                'verbose_name_plural': '02 Years',
                'ordering': ['-year'],
                'unique_together': {('year', 'institute')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ims_01_institute.class')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupNames', to='ims_01_institute.groupname')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ims_01_institute.institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ims_01_institute.year')),
            ],
            options={
                'verbose_name_plural': '05 Groups',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ims_01_institute.year'),
        ),
        migrations.CreateModel(
            name='MarkTypeForSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_type', models.CharField(choices=[('MCQ', 'Objective (MCQ)'), ('Theory', 'Theory'), ('Practical', 'Practical'), ('WR', 'Written(CQ)'), ('CA', 'Continuous Assessment'), ('CT', 'Class Test'), ('AE', 'Annual Exam')], max_length=50, verbose_name='Mark Type')),
                ('max_marks', models.PositiveIntegerField(default=0, verbose_name='Maximum Marks')),
                ('pass_marks', models.PositiveIntegerField(default=0, verbose_name='Pass Marks')),
                ('serial_number', models.PositiveIntegerField(default=0, verbose_name='Serial Number')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_types', to='ims_01_institute.subjectname', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': '9 Mark Type For Subject',
                'unique_together': {('subject', 'mark_type')},
            },
        ),
        migrations.CreateModel(
            name='SubjectForIMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Is it Optional')),
                ('serial_number', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('full_marks', models.PositiveIntegerField(default=100, verbose_name='Full Marks')),
                ('pass_marks', models.PositiveIntegerField(default=33, verbose_name='Pass Marks')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectforims', to='ims_01_institute.class', verbose_name='Class')),
                ('group', models.ManyToManyField(related_name='subjectforims', to='ims_01_institute.group', verbose_name='Groups')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectforims', to='ims_01_institute.institute', verbose_name='Institute')),
                ('subject_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectname', to='ims_01_institute.subjectname')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectforims', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '08 Subjects',
                'ordering': ['serial_number'],
                'indexes': [models.Index(fields=['institute', 'year', 'class_instance', 'subject_name'], name='ims_01_inst_institu_2ee083_idx')],
                'unique_together': {('class_instance', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ims_01_institute.class')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ims_01_institute.group')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ims_01_institute.institute')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionNames', to='ims_01_institute.sectionname')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ims_01_institute.year')),
            ],
            options={
                'verbose_name_plural': '06 Sections',
                'indexes': [models.Index(fields=['institute', 'year', 'class_instance', 'group', 'section_name'], name='ims_01_inst_institu_dda9c5_idx')],
                'unique_together': {('group', 'section_name')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['institute', 'year', 'class_instance', 'group_name'], name='ims_01_inst_institu_00a318_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('class_instance', 'group_name')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['institute', 'year', 'class_name', 'shift'], name='ims_01_inst_institu_7d36db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('institute', 'class_name', 'year', 'shift')},
        ),
    ]
