# Generated by Django 5.1.4 on 2025-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order'], 'verbose_name_plural': '05 Groups'},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Serial Number of Group'),
        ),
    ]
