# Generated by Django 5.1.4 on 2025-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0002_alter_group_options_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectname',
            name='serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], max_length=20),
        ),
    ]
