# Generated by Django 5.1.4 on 2025-08-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0003_subjectname_serial_alter_class_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectname',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
