# Generated by Django 5.1.4 on 2025-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0004_alter_subjectname_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectname',
            options={'ordering': ['class_name', 'serial', 'code'], 'verbose_name_plural': '07 Subject Names'},
        ),
    ]
