# Generated by Django 5.1.4 on 2025-08-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0005_alter_subjectname_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectname',
            options={'ordering': ['serial', 'code', 'class_name'], 'verbose_name_plural': '07 Subject Names'},
        ),
    ]
