# Generated by Django 5.1.4 on 2025-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0006_alter_subjectname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='education_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('general_high_school', 'General High School'), ('vocational', 'Vocational'), ('madrasa', 'Madrasa'), ('collage', 'Collage')], max_length=20, null=True),
        ),
    ]
