# Generated by Django 5.1.4 on 2025-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0008_alter_subjectname_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('all', 'All')], max_length=20),
        ),
    ]
