# Generated by Django 5.1.4 on 2025-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0009_alter_class_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], max_length=20),
        ),
    ]
