# Generated by Django 5.1.4 on 2025-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0010_alter_class_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectname',
            name='combined_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectname',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
