# Generated by Django 5.1.4 on 2025-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0011_subjectname_combined_group_subjectname_is_combined'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectname',
            name='is_displayed_on_marksheet',
            field=models.BooleanField(default=True),
        ),
    ]
