# Generated by Django 5.1.4 on 2025-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='institute_eiin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
