# Generated by Django 5.1.4 on 2025-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0013_institute_institute_eiin'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
