# Generated by Django 5.1.4 on 2025-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0014_institute_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name_eng', models.CharField(max_length=100, unique=True, verbose_name='Shift Name (English)')),
                ('shift', models.CharField(max_length=100, unique=True, verbose_name='Shift Name (Bangla)')),
                ('shift_name_eng_lowercase', models.CharField(max_length=100, verbose_name='Lowercase(morning)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': '01 Shifts',
                'ordering': ['shift_name_eng'],
            },
        ),
    ]
