# Generated by Django 5.1.4 on 2025-11-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0015_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
