# Generated by Django 5.1.4 on 2025-12-23 11:20

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0017_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='signature',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Signature of Head', null=True, upload_to=backend.utils.safe_upload_to_teacher_signature),
        ),
        migrations.AddField(
            model_name='institute',
            name='signature_cropped',
            field=image_cropping.fields.ImageRatioField('signature', '300x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='signature cropped'),
        ),
    ]
