# Generated by Django 5.1.4 on 2025-12-23 12:30

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0018_institute_signature_institute_signature_cropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='signature_cropped',
            field=image_cropping.fields.ImageRatioField('signature', '300x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='signature cropped'),
        ),
    ]
