# Generated by Django 5.1.4 on 2025-11-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0014_institute_website'),
        ('ims_02_account', '0025_alter_teachereducation_image_cropped'),
        ('ims_05_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_type', models.CharField(choices=[('daily', 'Daily'), ('subject', 'Subject Wise')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='ims_01_institute.class')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='ims_01_institute.group')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='ims_01_institute.institute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='ims_01_institute.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='ims_01_institute.year')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('institute', 'year', 'class_instance', 'group', 'section', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='ims_05_attendance.attendanceday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='ims_02_account.student')),
            ],
            options={
                'ordering': ['student__roll_number'],
                'unique_together': {('attendance_day', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
