# Generated by Django 5.1.4 on 2025-11-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0025_alter_teachereducation_image_cropped'),
        ('ims_05_attendance', '0002_attendanceday_studentattendance_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceday',
            name='attendance_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_attendances', to='ims_02_account.teacher'),
        ),
    ]
