# Generated by Django 5.1.4 on 2025-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_05_attendance', '0003_attendanceday_attendance_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('half_day', 'Half Day'), ('initial', 'Initial')], default='initial', max_length=20),
        ),
    ]
