# Generated by Django 5.1.4 on 2025-07-22 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Urgent', 'Urgent')], default='General', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='ims_01_institute.institute', verbose_name='Institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '03 Announcements',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Web', 'Web'), ('Email', 'Email'), ('SMS', 'SMS'), ('App Notification', 'App Notification')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ims_06_announcement.announcement')),
            ],
            options={
                'verbose_name_plural': '04 AnnouncementDeliverys',
            },
        ),
        migrations.CreateModel(
            name='AudienceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencegroup', to='ims_01_institute.institute', verbose_name='Institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencegroup', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '01 AudienceGroups',
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audiences', to='ims_01_institute.institute', verbose_name='Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audience', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='ims_01_institute.year', verbose_name='Year')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='ims_06_announcement.audiencegroup')),
            ],
            options={
                'verbose_name_plural': '02 Audiences',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.ManyToManyField(related_name='announcements', to='ims_06_announcement.audiencegroup'),
        ),
    ]
