# Generated by Django 5.1.4 on 2025-07-22 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_02_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='ims_01_institute.institute')),
            ],
            options={
                'verbose_name_plural': '01 Fee Types',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('scope', models.CharField(choices=[('YEAR', 'Year-Level (All Classes)'), ('CLASS', 'Class-Level'), ('GROUP', 'Group-Level')], default='YEAR', max_length=20)),
                ('class_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='ims_01_institute.class')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='ims_01_institute.group')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='ims_01_institute.institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='ims_01_institute.year')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='ims_2_feemanagement.feetype')),
            ],
            options={
                'verbose_name_plural': '02 Fee Structures',
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='ims_02_account.student')),
            ],
            options={
                'verbose_name_plural': '03 Student Accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ims_2_feemanagement.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ims_02_account.student')),
            ],
            options={
                'verbose_name_plural': '04 Transactions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_01_institute.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ims_02_account.student')),
                ('transactions', models.ManyToManyField(related_name='invoices', to='ims_2_feemanagement.transaction')),
            ],
            options={
                'verbose_name_plural': '05 Invoices',
            },
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['institute', 'name'], name='ims_2_feema_institu_2be3fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together={('institute', 'name')},
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['institute', 'year'], name='ims_2_feema_institu_41d9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['institute', 'year', 'class_instance'], name='ims_2_feema_institu_09e705_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['institute', 'year', 'class_instance', 'group'], name='ims_2_feema_institu_a325c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('institute', 'year', 'class_instance', 'group', 'fee_type', 'scope')},
        ),
        migrations.AddIndex(
            model_name='studentaccount',
            index=models.Index(fields=['student'], name='ims_2_feema_student_52fd30_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'is_paid'], name='ims_2_feema_student_37e8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'invoice_number'], name='ims_2_feema_student_acaaa2_idx'),
        ),
    ]
