# Generated by Django 5.1.4 on 2025-07-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ims_01_institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForIMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255, verbose_name='Exam Name in Bengali')),
                ('exam_name_in_english', models.CharField(max_length=255, verbose_name='Exam Name in English')),
                ('heighest_marks', models.FloatField(default=0.0, verbose_name='Highest Marks')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('class_instance', models.ManyToManyField(related_name='examforims', to='ims_01_institute.class', verbose_name='Groups')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examforims', to='ims_01_institute.institute', verbose_name='Institute')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examforims', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': '01 Exams',
                'indexes': [models.Index(fields=['institute', 'year', 'exam_name'], name='ims_03_exam_institu_42d02f_idx')],
                'unique_together': {('institute', 'year', 'exam_name')},
            },
        ),
    ]
