# Generated by Django 5.1.4 on 2025-11-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0013_institute_institute_eiin'),
        ('ims_03_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_day', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in timetable')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='ims_01_institute.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='ims_03_exam.examforims')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='ims_01_institute.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='ims_01_institute.subjectforims')),
            ],
            options={
                'ordering': ['exam', 'class_instance', 'group', 'order', 'exam_date'],
                'indexes': [models.Index(fields=['exam', 'class_instance', 'group', 'exam_date'], name='ims_03_exam_exam_id_fd26c7_idx')],
            },
        ),
    ]
