# Generated by Django 5.1.4 on 2025-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_03_exam', '0002_examroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
