# Generated by Django 5.1.4 on 2025-07-22 16:37

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(help_text='বাংলা নাম লিখুন', max_length=100, verbose_name='মেনুর নাম (বাংলা)')),
                ('name_en', models.CharField(blank=True, help_text='Optional: English version of the name', max_length=100, verbose_name='Menu Name (English)')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from English or Bengali name', max_length=150, unique=True)),
                ('url', models.CharField(blank=True, help_text='Custom URL (if needed), otherwise generated from slug', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of menu item')),
                ('is_active', models.BooleanField(default=True, help_text='Active/Inactive menu')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Set parent for dropdown or submenu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ims_20_website.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
