# Generated by Django 5.1.4 on 2025-07-23 16:46

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', image_cropping.fields.ImageCropField(upload_to='website/home-sliders/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '1920x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('slide_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '01 Slider',
                'verbose_name_plural': '01 Sliders',
                'ordering': ['slide_number'],
            },
        ),
    ]
