# Generated by Django 5.1.4 on 2025-07-24 15:54

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0005_alter_slider_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1920x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
