# Generated by Django 5.1.4 on 2025-07-24 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0006_alter_slider_cropping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(help_text='Full notice details')),
                ('attachment', models.FileField(blank=True, help_text='PDF/DOC/Image/etc. to download', null=True, upload_to='website/notice-attachments/')),
                ('is_important', models.BooleanField(default=False, help_text='Show this notice with priority/highlight')),
                ('pin_on_top', models.BooleanField(default=False, help_text='Always show this notice at the top')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expire_at', models.DateTimeField(blank=True, help_text='Optional auto-expiry', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who posted this notice?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-pin_on_top', '-is_important', '-published_at'],
            },
        ),
    ]
