# Generated by Django 5.1.4 on 2025-07-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0007_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='display_position',
            field=models.CharField(choices=[('homepage', 'Homepage Banner/Marquee'), ('dashboard', 'User Dashboard'), ('noticeboard', 'Notice Board Page Only')], default='noticeboard', help_text='Where this notice will be shown', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents')], default='all', help_text='Who is this notice for?', max_length=20),
        ),
    ]
