# Generated by Django 5.1.4 on 2025-07-26 11:56

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0008_notice_display_position_notice_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AddField(
            model_name='notice',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AddField(
            model_name='slider',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='display_position',
            field=models.CharField(choices=[('all', 'All'), ('homepage', 'Homepage Banner/Marquee'), ('dashboard', 'User Dashboard'), ('noticeboard', 'Notice Board Page Only')], default='noticeboard', help_text='Where this notice will be shown', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('parents', 'Parents')], default='all', help_text='Who is this notice for?', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoryOfInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', image_cropping.fields.ImageCropField(upload_to='website/home-sliders/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('show_image', models.BooleanField(default=False, help_text='Are you want to show image with history?')),
                ('institute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historyofinstitute', to='ims_01_institute.institute', verbose_name='Institute')),
            ],
            options={
                'verbose_name': '06 History of Institute',
                'verbose_name_plural': '06 HistoryOfInstitutes',
            },
        ),
    ]
