# Generated by Django 5.1.4 on 2025-07-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0009_menuitem_institute_notice_institute_slider_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofinstitute',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyofinstitute', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
    ]
