# Generated by Django 5.1.4 on 2025-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0010_alter_historyofinstitute_institute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyofinstitute',
            options={'verbose_name': '06_History_Of_Institute', 'verbose_name_plural': '06 History of Institutes'},
        ),
        migrations.AddField(
            model_name='historyofinstitute',
            name='content',
            field=models.TextField(default=1, help_text='Full History of Institute.'),
            preserve_default=False,
        ),
    ]
