# Generated by Django 5.1.4 on 2025-07-26 15:14

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0011_alter_historyofinstitute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', image_cropping.fields.ImageCropField(upload_to='website/home-sliders/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '520x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('message', models.TextField(help_text='Enter Message')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managingcommittee', to='ims_01_institute.institute', verbose_name='Institute')),
            ],
            options={
                'verbose_name': '07_Managing_Committee',
                'verbose_name_plural': '07 Managing Committee',
            },
        ),
    ]
