# Generated by Django 5.1.4 on 2025-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0012_managingcommittee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managingcommittee',
            options={'ordering': ['order'], 'verbose_name': '07_Managing_Committee', 'verbose_name_plural': '07 Managing Committee'},
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
