# Generated by Django 5.1.4 on 2025-07-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0013_alter_managingcommittee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_for_institute_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Headline for Institute Info')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('mobile_numbers', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobile Numbers')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('headline_for_info_center', models.CharField(blank=True, max_length=200, null=True, verbose_name='Headline for Info Center')),
                ('info_center_address', models.CharField(max_length=200, verbose_name='Address for Info Center')),
                ('info_center_mobile_numbers', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobile Numbers for Info Center')),
                ('info_center_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email for Info Center')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactinformation', to='ims_01_institute.institute', verbose_name='Institute')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
