# Generated by Django 5.1.4 on 2025-07-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0014_contactinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyofinstitute',
            options={'verbose_name': '05_History_Of_Institute', 'verbose_name_plural': '05 History of Institutes'},
        ),
        migrations.AlterModelOptions(
            name='managingcommittee',
            options={'ordering': ['order'], 'verbose_name': '06_Managing_Committee', 'verbose_name_plural': '06 Managing Committee'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': '01 Menu Item', 'verbose_name_plural': '01 Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pin_on_top', '-is_important', '-published_at'], 'verbose_name': '03 Notice', 'verbose_name_plural': '03 Notices'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['slide_number'], 'verbose_name': '02 Slider', 'verbose_name_plural': '02 Sliders'},
        ),
        migrations.CreateModel(
            name='StudentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boys', models.PositiveIntegerField(default=0)),
                ('girls', models.PositiveIntegerField(default=0)),
                ('muslim', models.PositiveIntegerField(default=0)),
                ('hindu', models.PositiveIntegerField(default=0)),
                ('bouddha', models.PositiveIntegerField(default=0)),
                ('christian', models.PositiveIntegerField(default=0)),
                ('muktijoddha', models.PositiveIntegerField(default=0)),
                ('shodosho_sontan', models.PositiveIntegerField(default=0)),
                ('autistic', models.PositiveIntegerField(default=0)),
                ('physical_disability', models.PositiveIntegerField(default=0)),
                ('class_instance', models.ForeignKey(help_text='The class (e.g., Six) of the student.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.class', verbose_name='Class')),
                ('group', models.ForeignKey(help_text='The group (e.g., Science, Arts) of the student.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.group', verbose_name='Group')),
                ('institute', models.ForeignKey(help_text='The institute associated with the result.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.institute', verbose_name='Institute')),
                ('section', models.ForeignKey(help_text='The section (e.g., A, B) of the student.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.section', verbose_name='Section')),
                ('year', models.ForeignKey(help_text='The academic year of the result.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.year', verbose_name='Year')),
            ],
            options={
                'verbose_name': '08 Student Statistics',
                'verbose_name_plural': '08 Student Statistics',
                'indexes': [models.Index(fields=['institute', 'year', 'class_instance', 'group', 'section'], name='ims_20_webs_institu_0588df_idx')],
            },
        ),
    ]
