# Generated by Django 5.1.4 on 2025-07-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0001_initial'),
        ('ims_20_website', '0015_alter_historyofinstitute_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstatistics',
            unique_together={('group', 'section')},
        ),
    ]
