# Generated by Django 5.1.4 on 2025-07-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0002_alter_group_options_group_order'),
        ('ims_20_website', '0016_alter_studentstatistics_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatistics',
            name='institute',
            field=models.ForeignKey(help_text='The institute associated with the Student Statistics.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='studentstatistics',
            name='year',
            field=models.ForeignKey(help_text='The academic year of the Student Statistics.', on_delete=django.db.models.deletion.CASCADE, related_name='studentstatistics', to='ims_01_institute.year', verbose_name='Year'),
        ),
    ]
