# Generated by Django 5.1.4 on 2025-08-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0010_alter_class_shift'),
        ('ims_20_website', '0017_alter_studentstatistics_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='ims_01_institute.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ims_01_institute.institute')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('show_image', models.BooleanField(default=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ims_01_institute.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('show_image', models.BooleanField(default=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='ims_01_institute.institute')),
            ],
        ),
    ]
