# Generated by Django 5.1.4 on 2025-08-08 10:36

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0018_achievement_facility_history_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='history',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '520x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='history',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/home-sliders/'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '520x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/home-sliders/'),
        ),
    ]
