# Generated by Django 5.1.4 on 2025-08-08 10:40

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0019_remove_history_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/history/'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/history/'),
        ),
    ]
