# Generated by Django 5.1.4 on 2025-08-08 10:45

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0020_alter_history_image_alter_introduction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '660x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '660x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
