# Generated by Django 5.1.4 on 2025-08-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0021_alter_history_cropping_alter_introduction_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managingcommittee',
            name='message',
            field=models.TextField(blank=True, help_text='Enter Message', null=True),
        ),
    ]
