# Generated by Django 5.1.4 on 2025-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0022_alter_managingcommittee_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingcommittee',
            name='show_image_on_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
