# Generated by Django 5.1.4 on 2025-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0023_managingcommittee_show_image_on_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pin_on_top', '-is_important', '-published_at'], 'verbose_name': '03 Notice', 'verbose_name_plural': 'Notices'},
        ),
    ]
