# Generated by Django 5.1.4 on 2025-08-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0024_alter_notice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='display_position',
            field=models.CharField(choices=[('all', 'All'), ('dashboard', 'User Dashboard'), ('noticeboard', 'Notice Board Page Only')], default='noticeboard', help_text='Where this notice will be shown', max_length=20),
        ),
    ]
