# Generated by Django 5.1.4 on 2025-08-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0025_notice_is_marquee_alter_notice_display_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='display_position',
            field=models.CharField(choices=[('all', 'All'), ('dashboard', 'User Dashboard'), ('noticeboard', 'Notice Board Page Only')], default='all', help_text='Where this notice will be shown', max_length=20),
        ),
    ]
