# Generated by Django 5.1.4 on 2025-08-29 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0026_alter_notice_display_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
