# Generated by Django 5.1.4 on 2025-08-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0027_alter_notice_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., আমাদের বিষয়ে, নোটিশ, একাডেমিক', max_length=100, unique=True, verbose_name='Card Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title, used for URLs', max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order of cards')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CardItem', to='ims_01_institute.institute')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Feature Text')),
                ('link', models.CharField(max_length=200, verbose_name='Feature Link')),
                ('icon', models.CharField(blank=True, help_text='Optional: React icon component name (e.g., User, BookOpen)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ims_20_website.carditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
