# Generated by Django 5.1.4 on 2025-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0029_alter_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated from title, used for URLs', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Feature Link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated from English or Bengali name', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
        ),
    ]
