# Generated by Django 5.1.4 on 2025-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0030_alter_carditem_slug_alter_feature_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='link',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated from link, used for URLs', max_length=120, unique=True, verbose_name='Feature Link'),
        ),
    ]
