# Generated by Django 5.1.4 on 2025-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0032_alter_feature_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: React icon component name (e.g., User, BookOpen)', max_length=50, null=True),
        ),
    ]
