# Generated by Django 5.1.4 on 2025-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0033_carditem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active/Inactive on website'),
        ),
    ]
