# Generated by Django 5.1.4 on 2025-09-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0035_alter_feature_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='institute',
        ),
        migrations.CreateModel(
            name='InstituteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year of establishment, e.g., 1976', null=True, verbose_name='প্রতিষ্ঠিত')),
                ('total_students', models.CharField(blank=True, help_text='Number of students, e.g., "২৭০০+"', max_length=20, null=True, verbose_name='শিক্ষার্থী')),
                ('total_teachers', models.CharField(blank=True, help_text='Number of teachers, e.g., "20+"', max_length=20, null=True, verbose_name='শিক্ষক')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.OneToOneField(help_text='Select the institute this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ims_01_institute.institute')),
            ],
            options={
                'verbose_name': 'Institute Detail',
                'verbose_name_plural': 'Institute Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='institute_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ims_20_website.institutedetail'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='institute_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='ims_20_website.institutedetail'),
        ),
    ]
