# Generated by Django 5.1.4 on 2025-09-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0036_remove_history_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='ims_20_website.institutedetail'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ims_20_website.institutedetail'),
        ),
    ]
