# Generated by Django 5.1.4 on 2025-09-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0037_alter_achievement_institute_alter_facility_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetail',
            name='institute',
            field=models.OneToOneField(help_text='Select the institute this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ims_01_institute.institute', verbose_name='প্রতিষ্ঠানের নাম'),
        ),
    ]
