# Generated by Django 5.1.4 on 2025-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0038_alter_institutedetail_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetail',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of establishment, e.g., 1976', null=True, verbose_name='Establishment Year'),
        ),
        migrations.AlterField(
            model_name='institutedetail',
            name='total_students',
            field=models.CharField(blank=True, help_text='Number of students, e.g., "২৭০০+"', max_length=20, null=True, verbose_name='Total Students'),
        ),
        migrations.AlterField(
            model_name='institutedetail',
            name='total_teachers',
            field=models.CharField(blank=True, help_text='Number of teachers, e.g., "20+"', max_length=20, null=True, verbose_name='Total Teachers'),
        ),
    ]
