# Generated by Django 5.1.4 on 2025-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0039_alter_institutedetail_established_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetail',
            name='established_year',
            field=models.CharField(blank=True, help_text='Year of establishment, e.g., 1976', max_length=20, null=True, verbose_name='Establishment Year'),
        ),
    ]
