# Generated by Django 5.1.4 on 2025-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0040_alter_institutedetail_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
