# Generated by Django 5.1.4 on 2025-09-01 16:57

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0041_alter_history_content_alter_introduction_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '660x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/history/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
    ]
