# Generated by Django 5.1.4 on 2025-09-02 01:19

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0042_facility_cropping_facility_image_facility_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutedetail',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('heading_background_image', '1400x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='institutedetail',
            name='heading_background_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/history/'),
        ),
        migrations.AddField(
            model_name='institutedetail',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='institutedetail',
            name='institute',
            field=models.OneToOneField(help_text='Select the institute this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ims_01_institute.institute'),
        ),
    ]
