# Generated by Django 5.1.4 on 2025-09-02 04:38

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0043_institutedetail_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetail',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('heading_background_image', '1280x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Page title (e.g., যোগাযোগ)', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactinformation', to='ims_01_institute.institute', verbose_name='Institute')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Card title (e.g., যোগাযোগের ঠিকানা)', max_length=255, null=True)),
                ('name', models.CharField(help_text='Person name (e.g., সেলিনা সুলতানা)', max_length=255)),
                ('designation', models.CharField(blank=True, help_text='Designation (e.g., প্রধান শিক্ষক)', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address (multi-line)', null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50, null=True)),
                ('is_whatsapp', models.BooleanField(default=False, help_text='Is this a WhatsApp number?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering for display (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this card on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ims_20_website.contactpage')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
