# Generated by Django 5.1.4 on 2025-09-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_02_account', '0008_student_fathers_name_student_mothers_name_and_more'),
        ('ims_20_website', '0044_alter_institutedetail_cropping_contactpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contact_Person', to='ims_02_account.teacher'),
        ),
    ]
