# Generated by Django 5.1.4 on 2025-09-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0045_contactcard_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='is_whatsapp',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='phone',
        ),
    ]
