# Generated by Django 5.1.4 on 2025-09-03 17:27

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0046_remove_contactcard_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF/DOC/Image/etc. to download', null=True, upload_to=backend.utils.safe_upload_to_notice_attachments),
        ),
    ]
