# Generated by Django 5.1.4 on 2025-09-03 18:36

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0047_alter_notice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_institute_details_attachments),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_institute_details_attachments),
        ),
        migrations.AlterField(
            model_name='institutedetail',
            name='heading_background_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_institute_details_attachments),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_institute_details_attachments),
        ),
    ]
