# Generated by Django 5.1.4 on 2025-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0048_alter_facility_image_alter_history_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
