# Generated by Django 5.1.4 on 2025-09-10 16:01

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0049_alter_facility_description_alter_facility_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='cropping',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '1900x785', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_slides),
        ),
    ]
