# Generated by Django 5.1.4 on 2025-09-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0050_remove_slider_cropping_slider_image_cropped_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOfInstitute',
        ),
    ]
