# Generated by Django 5.1.4 on 2025-09-11 08:18

import backend.utils
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0051_delete_historyofinstitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managingcommittee',
            name='cropping',
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '300x370', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
        migrations.AlterField(
            model_name='managingcommittee',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_committee),
        ),
    ]
