# Generated by Django 5.1.4 on 2025-09-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0052_remove_managingcommittee_cropping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pin_on_top', '-is_important', '-published_at'], 'verbose_name': 'Notice', 'verbose_name_plural': '03 Notices'},
        ),
    ]
