# Generated by Django 5.1.4 on 2025-09-11 10:17

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0053_alter_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carditem',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Page Card Link', 'verbose_name_plural': '05 Page Card Link'},
        ),
        migrations.AlterModelOptions(
            name='institutedetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Institute Detail', 'verbose_name_plural': '04 Institute Details'},
        ),
        migrations.RemoveField(
            model_name='institutedetail',
            name='cropping',
        ),
        migrations.AddField(
            model_name='institutedetail',
            name='heading_background_image_cropped',
            field=image_cropping.fields.ImageRatioField('heading_background_image', '1280x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='heading background image cropped'),
        ),
    ]
