# Generated by Django 5.1.4 on 2025-09-11 10:30

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0054_alter_carditem_options_alter_institutedetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='history',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='cropping',
        ),
        migrations.AddField(
            model_name='facility',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
        migrations.AddField(
            model_name='history',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '500x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='image_cropped',
            field=image_cropping.fields.ImageRatioField('image', '500x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped'),
        ),
    ]
