# Generated by Django 5.1.4 on 2025-09-11 10:32

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0055_remove_facility_cropping_remove_history_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedetail',
            name='heading_background_image_cropped',
            field=image_cropping.fields.ImageRatioField('heading_background_image', '1400x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='heading background image cropped'),
        ),
    ]
