# Generated by Django 5.1.4 on 2025-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0057_alter_institutedetail_heading_background_image_cropped'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstatistics',
            unique_together={('institute', 'year', 'class_instance', 'group', 'section')},
        ),
    ]
