# Generated by Django 5.1.4 on 2025-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0058_alter_studentstatistics_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstatistics',
            unique_together={('group', 'section')},
        ),
    ]
