# Generated by Django 5.1.4 on 2025-09-13 16:46

import backend.utils
import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0012_subjectname_is_displayed_on_marksheet'),
        ('ims_20_website', '0059_alter_studentstatistics_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managingcommittee',
            options={'ordering': ['-formation_date'], 'verbose_name': '06_Managing_Committee', 'verbose_name_plural': '06 Managing Committees'},
        ),
        migrations.RenameField(
            model_name='managingcommittee',
            old_name='image',
            new_name='image_document',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='image_cropped',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='message',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='show_image_on_sidebar',
        ),
        migrations.RemoveField(
            model_name='managingcommittee',
            name='title',
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='বর্তমান কমিটি?'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='approved_by',
            field=models.CharField(blank=True, help_text='যেমন: শিক্ষা বোর্ড, শিক্ষা মন্ত্রণালয়', max_length=255, null=True, verbose_name='অনুমোদনকারী কর্তৃপক্ষ'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='committee_name',
            field=models.CharField(default='Managing Committee', max_length=255, verbose_name='কমিটির নাম'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='description',
            field=models.TextField(blank=True, help_text='কমিটির সংক্ষিপ্ত বিবরণ / উদ্দেশ্য', null=True),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='কমিটির মেয়াদ শেষ হওয়ার তারিখ'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='formation_date',
            field=models.DateField(blank=True, null=True, verbose_name='কমিটি গঠনের তারিখ'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='image_document_cropped',
            field=image_cropping.fields.ImageRatioField('image_document', '800x1120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image document cropped'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='অতিরিক্ত মন্তব্য'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_committee, verbose_name='কমিটি অনুমোদন নথি'),
        ),
        migrations.AddField(
            model_name='managingcommittee',
            name='total_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='কমিটিতে সদস্য সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='managingcommittee',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managing_committees', to='ims_01_institute.institute', verbose_name='Institute'),
        ),
        migrations.CreateModel(
            name='ManagingCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম/পদবি (যেমন: সভাপতি)')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('designation', models.CharField(max_length=200, verbose_name='দায়িত্ব (যেমন: সদস্য)')),
                ('image', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_committee, verbose_name='ছবি')),
                ('image_cropped', image_cropping.fields.ImageRatioField('image', '300x370', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped')),
                ('message', models.TextField(blank=True, help_text='সংক্ষিপ্ত বার্তা বা বক্তব্য', null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='মোবাইল নম্বর')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ইমেইল')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ঠিকানা')),
                ('social_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('social_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('show_image_on_sidebar', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ims_20_website.managingcommittee', verbose_name='Managing Committee')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['order'],
            },
        ),
    ]
