# Generated by Django 5.1.4 on 2025-09-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0060_alter_managingcommittee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managingcommittee',
            name='committee_name',
        ),
    ]
