# Generated by Django 5.1.4 on 2025-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0061_remove_managingcommittee_committee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, help_text='Full notice details', null=True),
        ),
    ]
