# Generated by Django 5.1.4 on 2025-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0062_alter_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingcommittee',
            name='show_in_website',
            field=models.BooleanField(default=True, verbose_name='ওয়েবসাইটে দেখতে চান?'),
        ),
    ]
