# Generated by Django 5.1.4 on 2025-09-25 10:28

import backend.utils
import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0013_institute_institute_eiin'),
        ('ims_20_website', '0063_managingcommittee_show_in_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date (English)')),
                ('authority_bn', models.CharField(max_length=255, verbose_name='প্রদানকারী কর্তৃপক্ষ (বাংলা)')),
                ('authority_en', models.CharField(max_length=255, verbose_name='Authority (English)')),
                ('image', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=backend.utils.safe_upload_to_website_institute_approval)),
                ('image_cropped', image_cropping.fields.ImageRatioField('image', '800x1120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ims_01_institute.institute')),
            ],
            options={
                'verbose_name': 'Institute Document',
                'verbose_name_plural': 'Institute Documents',
                'ordering': ['-issue_date'],
            },
        ),
    ]
