# Generated by Django 5.1.4 on 2025-09-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_01_institute', '0013_institute_institute_eiin'),
        ('ims_20_website', '0064_institutedocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstituteDocument',
            new_name='InstituteApprovalInfo',
        ),
    ]
