# Generated by Django 5.1.4 on 2025-09-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0065_rename_institutedocument_instituteapprovalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteapprovalinfo',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Institute Document', 'verbose_name_plural': 'Institute Approval Info'},
        ),
    ]
