# Generated by Django 5.1.4 on 2025-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_20_website', '0067_alter_feature_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='link',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated from link, used for URLs', max_length=120, verbose_name='Feature Link'),
        ),
    ]
